# Generated by Django 4.2.7 on 2026-01-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todoitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
